
name: Build Package

on: [push, pull_request, release]

jobs:
  build_wheels:
    name: Build wheels on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        # os: [ubuntu-20.04, windows-2019, macOS-10.15]
        os: [ubuntu-20.04]

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2

      - name: Set up QEMU
        if: runner.os == 'Linux'
        uses: docker/setup-qemu-action@v1
        with:
          platforms: all

      - name: Build wheels
        uses: pypa/cibuildwheel@v2.2.2
        env:
          # configure cibuildwheel to build native archs ('auto'), and some
          # emulated ones
          CIBW_ARCHS_LINUX: auto aarch64 ppc64le s390x
          CIBW_AFTER_BUILD: python -m pip install -r ${{ runner.workspace }}/requirements.txt cibuildwheel
          CIBW_TEST_COMMAND: python -c 'import os, pathlib, sys, use; sys.path.insert(1, str(pathlib.Path(use.__file__).parent.parent.parent)); import justuse.unit_test, justuse.tdd_test; sys.argv.extend(["-m", "", "justuse/unit_test.py", "justuse/tdd_test.py"]); import pytest; pytest.main()'
          CIBW_TEST_REQUIRES: pytest pytest-env requests packaging==21.0 pydantic pip==21.2.1 furl wheel icontract beartype
          CIBW_BUILD_VERBOSITY: -vvv
          CIBW_PACKAGE: justuse
          CIBW_PROJECT_ROOT: ${{ runner.workspace }}
          CIBW_ROOT: ${{ runner.workspace }}
          CIBW_PROJECT_DIT: ${{ runner.workspace }}
          CIBW_DIR: ${{ runner.workspace }}
          CIBW_BUILDDIR: ${{ runner.workspace }}
          CIBW_BUILD_DIR: ${{ runner.workspace }}
          CIBW_BUILD: cp39-*

      - uses: actions/upload-artifact@v2
        with:
          path: ./wheelhouse/*.whl


