name: CIBuildWheels

on: [push, pull_request, release]

jobs:
  build_wheels:
    name: Build wheels on ${{ matrix.config.name }}
    runs-on: ${{ matrix.config.os }}
    strategy:
      fail-fast: true
      matrix:
        config:
          - name: "win32-x86"
            os: windows-2019
            arch: x86
          - name: "win32-amd64"
            os: windows-2019
            arch: AMD64

          - name: "macos-x84_64"
            os: macos-10.15
            arch: x86_64
          - name: "macos-universal2"
            os: macos-10.15
            arch: universal2

          - name: "linux-i386"
            os: ubuntu-20.04
            arch: i686
            platform: i386
          - name: "linux-x86_64"
            os: ubuntu-20.04
            arch: x86_64
            platform: x86_64
          - name: "linux-aarch64"
            os: ubuntu-20.04
            arch: aarch64
            platform: aarch64
          - name: "linux-ppc64le"
            os: ubuntu-20.04
            arch: ppc64le
            platform: ppc64le
          - name: "linux-s390x"
            os: ubuntu-20.04
            arch: s390x
            platform: s390x

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2

      - name: Set up QEMU
        if: ${{ startsWith(matrix.config.os, 'ubuntu') }}
        uses: docker/setup-qemu-action@v1
        with:
          platforms: ${{ matrix.config.platform }}

      - name: Build wheels
        uses: pypa/cibuildwheel@v2.2.2
        env:
          CIBW_BUILD_VERBOSITY: 3
          # hope that only the one corresponding to the current arch applies
          CIBW_ARCHS_WINDOWS: ${{ matrix.config.arch }}
          CIBW_ARCHS_MACOS: ${{ matrix.config.arch }}
          CIBW_ARCHS_LINUX: ${{ matrix.config.arch }}

      - uses: actions/upload-artifact@v2
        with:
          path: ./wheelhouse/*.whl
